apiVersion: v1
name: istio-operator
version: 1.14.3-bb.0
appVersion: 1.14.3
tillerVersion: ">=2.7.2"
description: Helm chart for deploying Istio operator
keywords:
  - istio
  - operator
sources:
  - https://github.com/istio/istio/tree/master/operator
engine: gotpl
icon: https://istio.io/latest/favicons/android-192x192.png
annotations:
  bigbang.dev/applicationVersions: |
    - Istio Operator: 1.14.3
    - Tetrate Istio Distro Operator: 1.13.5
