apiVersion: v1
name: istio-operator
version: 1.17.2-bb.0
appVersion: 1.17.2
tillerVersion: ">=2.7.2"
description: Helm chart for deploying Istio operator
keywords:
  - istio
  - operator
sources:
  - https://github.com/istio/istio/tree/master/operator
engine: gotpl
icon: https://istio.io/latest/favicons/android-192x192.png
annotations:
  bigbang.dev/applicationVersions: |
    - Istio Operator: 1.17.2
    - Tetrate Istio Distro Operator: 1.16.1
  helm.sh/images: |
    - name: operator
      image: registry1.dso.mil/ironbank/opensource/istio/operator:1.17.2
    - name: tetrate-operator
      condition: enterprise
      image: registry1.dso.mil/ironbank/tetrate/istio/operator:1.16.1-tetratefips-v1
