hub: registry1.dso.mil/ironbank/opensource/istio
## Added by Big Bang
image: operator
tag: 1.11.2

# ImagePullSecrets for operator ServiceAccount, list of secrets in the same namespace
# used to pull operator image. Must be set for any cluster configured with private docker registry.
imagePullSecrets: []

operatorNamespace: istio-operator

# Used to replace istioNamespace to support operator watch multiple namespaces.
watchedNamespaces: istio-system
waitForResourcesTimeout: 300s

# Used for helm2 to add the CRDs to templates.
enableCRDTemplates: false

# revision for the operator resources
revision: ""

# Operator resource defaults
operator:
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi

## Big Bang Additions below this line ##
createNamespace: true

nodeSelector: {}

affinity: {}

# Future: Toggles deployment of serviceMonitor + networkPolicy
# Only toggles networkPolicy right now
monitoring:
  enabled: false

networkPolicies:
  enabled: false
  # See `kubectl cluster-info` and then resolve to IP
  controlPlaneCidr: 0.0.0.0/0
